// Generated by https://quicktype.io
export interface IHubSiteDataResult {
  value: string;
}

export interface IHubSiteData {
  headerEmphasis:         string;
  themeKey:               string;
  name:                   string;
  url:                    string;
  logoUrl:                string;
  logoFileHash:           number;
  usesMetadataNavigation: boolean;
  megaMenuEnabled:        boolean;
  navigation?:            INavigation[];
  isNavAudienceTargeted:  boolean;
  siteDesignId:           string;
  requiresJoinApproval:   boolean;
  hideNameInNavigation:   boolean;
  parentHubSiteId:        string;
  relatedHubSiteIds:      string;
  tenantInstanceId:       string;
  isSameTenantInstance:   boolean;
}

export interface ISiteNavigationResult {
  value: INavigation[];
}

export interface INavigation {
  Id:               number;
  Title:            string;
  Url:              string;
  IsDocLib:         boolean;
  IsExternal:       boolean;
  ParentId:         number;
  ListTemplateType: number;
  AudienceIds:      string;
  CurrentLCID:      number;
  Children?:        INavigation[];
  IsVisible?:       boolean;
}
